"""Add qa_text field

Revision ID: 49b711d2aba8
Revises: f8faeae5ecde
Create Date: 2026-03-08 16:14:55.227941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b711d2aba8'
down_revision = 'f8faeae5ecde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qa_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_column('qa_text')

    # ### end Alembic commands ###
