"""Initial Schema

Revision ID: 704755926c31
Revises: 
Create Date: 2026-02-22 19:10:44.486318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704755926c31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('problem_text', sa.Text(), nullable=True),
    sa.Column('concepts_text', sa.Text(), nullable=True),
    sa.Column('solution_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenges')
    # ### end Alembic commands ###
